name: Loon2Egern Converter

on:
  push:
    paths:
      - 'Loon/Plugin/**'
    branches: [ main ]

jobs:
  convert:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install Dependencies
      run: |
        pip install pyyaml
        pip install egern-sdk==1.2.0  # 语法校验工具[1](@ref)
        
    - name: Run Conversion
      run: |
        set -euo pipefail
        mkdir -p Egern/Module
        python convert.py Loon/Plugin Egern/Module || {
          echo "::error::Conversion failed, check config syntax"
          exit 1
        }
        
    - name: Validate Syntax
      run: |
        for file in Egern/Module/*.yaml; do
          egern validate $file || exit 1
        done
        
    - name: Commit Changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add Egern/Module/
        git commit -m "Auto-converted Loon rules to Egern format [skip ci]" || true
        git push
