name: Convert Loon Plugin to Egern Module

on:
  push:
    branches: [ main ]
    paths:
      - 'Loon/Plugin/**.plugin'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install Dependencies
        run: npm install js-yaml
        
      - name: Convert Plugins
        run: node convert.js
        
      - name: Commit Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add Egern/Module/*.yaml
          git commit -m "Convert Loon plugins to Egern modules" || echo "No changes to commit"
          git push