name: Update Loon and Egern Rules

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

permissions:
  actions: write
  contents: write

jobs:
  UpdateRules:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Loon Rules
        run: |
          mkdir -p Loon/Rule Temp
          declare -A rules=(
            ["Telegram"]="https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/Telegram/Telegram.list"
            ["YouTube"]="https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/YouTube/YouTube.list"
            ["Twitter"]="https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/Twitter/Twitter.list"
            ["Spotify"]="https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/Spotify/Spotify.list"
            ["AI"]="https://raw.githubusercontent.com/sooyaaabo/Loon/refs/heads/main/Rule/AI.list"
            ["TikTok"]="https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/TikTok/TikTok.list"
            ["Instagram"]="https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/Instagram/Instagram.list"
            ["GitHub"]="https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/GitHub/GitHub.list"
            ["Emby"]="https://raw.githubusercontent.com/Repcz/Tool/refs/heads/X/Loon/Rules/Emby.list"
            ["Google"]="https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/Google/Google.list"
          )
          for name in "${!rules[@]}"; do
            url=${rules[$name]}
            echo "Downloading $name from $url"
            if curl -L -H "User-Agent: Surge iOS/3450" "$url" -o "Temp/$name.list" --fail; then
              echo "$url" > "Temp/$name.url"
              echo "Successfully downloaded $name"
            else
              echo "Failed to download $name from $url" >> error.log
            fi
          done
          ls -la Temp/ > temp_download_contents.log

      - name: Process Loon Rules
        run: |
          for file in Temp/*.list; do
            if [[ -f "$file" ]]; then
              file_name=$(basename "$file" .list)
              if [[ "$file_name" == "Emby" ]]; then
                url="Skipped URL"
              elif [[ -f "Temp/$file_name.url" ]]; then
                url=$(cat "Temp/$file_name.url")
              else
                url="Unknown URL"
                echo "Warning: Temp/$file_name.url not found for $file_name" >> warning.log
              fi
              sed -i '/^#/d' "$file"
              sed -i -e '/^PROCESS-NAME/d' "$file"
              line_count=$(grep -v '^$' "$file" | wc -l)
              {
                echo "# 规则名称: $file_name"
                echo "# 规则统计: $line_count"
                echo ""
                cat "$file"
              } > tmpfile
              mv tmpfile "$file"
              mv "$file" "Loon/Rule/$file_name.list"
            else
              echo "$file not found."
            fi
          done
          ls -la Temp/ > temp_process_contents.log

      - name: Convert to Egern Format
        run: |
          mkdir -p Egern/Rule
          for file in Loon/Rule/*.list; do
            if [[ -f "$file" ]]; then
              file_name=$(basename "$file" .list)
              yaml_file="Egern/Rule/$file_name.yaml"
              cp "$file" "$yaml_file"
              if [[ "$file_name" == "Emby" ]]; then
                url="Skipped URL"
              elif [[ -f "Temp/$file_name.url" ]]; then
                url=$(cat "Temp/$file_name.url")
              else
                url="Unknown URL"
                echo "Warning: Temp/$file_name.url not found for $file_name" >> warning.log
              fi
              sed -i '/^#/d' "$yaml_file"
              sed -i -e '/^USER-AGENT/d' -e '/^PROCESS-NAME/d' -e '/^AND/d' -e '/^OR/d' -e '/^NOT/d' "$yaml_file"
              # Initialize variables to track category insertion
              declare -A categories
              categories=(
                ["DOMAIN"]="domain_set"
                ["DOMAIN-SUFFIX"]="domain_suffix_set"
                ["DOMAIN-KEYWORD"]="domain_keyword_set"
                ["DOMAIN-WILDCARD"]="domain_wildcard_set"
                ["IP-CIDR"]="ip_cidr_set"
                ["IP-CIDR6"]="ip_cidr6_set"
                ["IP-ASN"]="asn_set"
                ["URL-REGEX"]="url_regex_set"
                ["DEST-PORT"]="dest_port_set"
                ["GEOIP"]="geoip_set"
              )
              # Create a temporary file for processing
              touch tmpfile
              echo "" > tmpfile
              has_no_resolve=false
              # Process each line and group by category
              while IFS= read -r line; do
                if [[ -z "$line" ]]; then
                  continue
                fi
                for category in "${!categories[@]}"; do
                  if [[ "$line" =~ ^${category}, ]]; then
                    if [[ -z "${inserted[${categories[$category]}]}" ]]; then
                      echo "${categories[$category]}:" >> tmpfile
                      inserted[${categories[$category]}]=1
                    fi
                    if [[ "$line" =~ no-resolve$ ]]; then
                      has_no_resolve=true
                      line=${line%,no-resolve}
                    fi
                    rule=${line#${category},}
                    if [[ "$category" == "URL-REGEX" ]]; then
                      echo "  - \"$rule\"" >> tmpfile
                    else
                      echo "  - $rule" >> tmpfile
                    fi
                    break
                  fi
                done
              done < "$yaml_file"
              # Add no_resolve if applicable
              {
                echo "# 规则名称: $file_name"
                echo "# 规则统计: $(grep -c '^  - ' tmpfile)"
                echo ""
                if [[ "$has_no_resolve" == true ]]; then
                  echo "no_resolve: true"
                  echo ""
                fi
                cat tmpfile
              } > "$yaml_file"
              rm tmpfile
            else
              echo "$file not found."
            fi
          done
          ls -la Temp/ > temp_egern_contents.log
          rm -rf Temp

      - name: Commit Changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add Loon/Rule/*.list Egern/Rule/*.yaml
          if git status -s | grep -q .; then
            git commit -m "Update Loon and Egern Rules $(date +'%Y-%m-%d %H:%M:%S')"
            git push
          else
            echo "No changes to commit."
          fi

      - name: Clean Workflow Runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          retain_days: 0
          keep_minimum_runs: 12